apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ch9n7be9o-nodejs
  janus-idp.io/tekton: ch9n7be9o-nodejs
  backstage.io/kubernetes-id: ch9n7be9o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ch9n7be9o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
